<?php
    $images = $this->getImages();
    $hashtag = $this->getHashtag();
?>
<?php if (count($images) || $hashtag) : ?>
    <div class="neklo-instagram">
        <?php if ($this->getTitle()) : ?>
            <div class="neklo-instagram-title">
                <span><?php echo $this->escapeHtml(str_replace('%s', $hashtag, $this->getTitle())) ?></span>
            </div>
        <?php endif; ?>
        
        <?php if ($this->getDescription()) : ?>
            <div class="neklo-instagram-description">
                <span><?php echo nl2br($this->escapeHtml(str_replace('%s', $hashtag, $this->getDescription()))) ?></span>
            </div>
        <?php endif; ?>
        
        <?php if (count($images)): ?>
            <ul class="neklo-instagram-list">
                <?php foreach ($images as $image) : ?>
                    <li>
                        <a href="<?php echo $image->getLink(); ?>" target="_blank" >
                            <i class="neklo-instagram-over"></i>
                            <img src="<?php echo $image->getUrl(); ?>" width="<?php echo intval($this->getImageWidth()) ?>" height="<?php echo intval($this->getImageHeight()) ?>" alt="<?php echo $this->escapeHtml($image->getName()); ?>" title="<?php echo $this->escapeHtml($image->getName()); ?>" />
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>